backend:
  name: github
  repo: nickbelo/media-slider-dynamic
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: slides
    label: Slides
    files:
      - file: content/slides.json
        label: Slides Config
        name: slides
        format: json
        fields:
          - name: slides
            label: Slides
            widget: list
            fields:
              - { name: type, label: Type, widget: select, options: ["image","video","youtube","website"] }
              - { name: duration, label: Duration (ms), widget: number, required: false }
              - { name: src, label: Source (image/video), widget: string, required: false }
              - { name: url, label: URL (youtube/website), widget: string, required: false }